

tail_solid  = { 1, 1, 1, 1 };
tail_liquid = { 0.9, 0.9, 0.9, 0.05 };

dofile(current_mod_path .. '/Weapons/Loadouts/jas39_m71ld.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_m71hd.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_sdb.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_gbu-31-blu109.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_gbu-38.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_gbu-12.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_gbu-49.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_mk82.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_mk83.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_mk84.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_aim-9l.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_iris-t.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_aim-120b.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_meteor.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_aim-120c5.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_aim-120c7.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_m70b.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_a-darter.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_mar-1.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_brimstone.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_spear-3.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_spear-ew.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_litening.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_ews39.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_elint.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_tank1100.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_aim-9m.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_aim-9x.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_python-5.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_gbu-31.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_gbu-32.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_gbu-10.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_gbu-16.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_dws39_arm.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_dws39_tv.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_rbs-15.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_rbs-15ai.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_stormshadow_arm.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_kepd-350_arm.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_asraam.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_flir.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_derby.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_agm-65k.lua')
dofile(current_mod_path .. '/Weapons/Loadouts/jas39_agm-65h.lua')

-- dofile(current_mod_path .. '/Weapons/Loadouts/jas39_tank1700.lua')