start_custom_command   = 10100
local __count_custom = start_custom_command-1
local function __custom_counter()
	__count_custom = __count_custom + 1
	return __count_custom
end
-------------------------------------------------------
--KEYS
-------------------------------------------------------
Keys =
{	
    Trigger      	     					= __custom_counter(),	
	GearUp					                = __custom_counter(),
	GearDown                                = __custom_counter(),
	MassSafe                                = __custom_counter(),
	MassStby                                = __custom_counter(),
	MassLive                                = __custom_counter(),
	Start                       			= __custom_counter(),
	Main                        			= __custom_counter(),
	APU                         			= __custom_counter(),
	ThrottleStop							= __custom_counter(),	
	LandingLights           				= __custom_counter(),
	TaxiLights                              = __custom_counter(),
	LandingTaxiLightsOff                    = __custom_counter(),
	WeaponJettison              			= __custom_counter(),
	WeaponJettisonCover						= __custom_counter(),
	TankJettison                			= __custom_counter(),
	TankJettisonCover						= __custom_counter(),
	Fuel                        			= __custom_counter(),
	FuelCover								= __custom_counter(),
	ParkingBrake                			= __custom_counter(),
	FloodLight                  			= __custom_counter(),
	IndicatorLight                  		= __custom_counter(),
	SeatUpDown                     			= __custom_counter(),
	NavigationLights            			= __custom_counter(),
	AntiCollisionLights         			= __custom_counter(),
	CanopyJettison              			= __custom_counter(),
	CanopyLever                 			= __custom_counter(),
	MasterCaution							= __custom_counter(),
	CovertLights	                        = __custom_counter(),
	FormationLights                        	= __custom_counter(),
	NavFlashLights							= __custom_counter(),
	SeatEject                               = __custom_counter(),
	SeatArm                                 = __custom_counter(),
	DTU                                     = __custom_counter(),
	TriggerSafe                             = __custom_counter(),
	TriggerSafeHold                         = __custom_counter(),
	CannonMode                              = __custom_counter(),
	CountermeasureRelease					= __custom_counter(),	
	AARProbeCover                          	= __custom_counter(),
	AARProbe                               	= __custom_counter(),
	EmergencyJettisonCover                  = __custom_counter(),
	EmergencyJettison                       = __custom_counter(),
	LadderChocks	                        = __custom_counter(),
	
	GripenPlaneUpStart			            = __custom_counter(),
	GripenPlaneDownStart		            = __custom_counter(),
	GripenPlaneLeftStart		            = __custom_counter(),
	GripenPlaneRightStart		            = __custom_counter(),
	GripenPlaneLeftRudderStart	            = __custom_counter(),
	GripenPlaneRightRudderStart             = __custom_counter(),
	GripenThrottleIncrease					= __custom_counter(),
	GripenThrottleDecrease           	  	= __custom_counter(),
	GripenThrottleStop						= __custom_counter(),
	GripenPlaneUpStop		                = __custom_counter(),
	GripenPlaneDownStop		                = __custom_counter(),
	GripenPlaneLeftStop		                = __custom_counter(),
	GripenPlaneRightStop		            = __custom_counter(),
	GripenPlaneLeftRudderStop               = __custom_counter(),
	GripenPlaneRightRudderStop              = __custom_counter(),


-------------------------------------------------------
--FC3 Commands
-------------------------------------------------------
	ICommandHUDBrightnessDown	            = 747,
	ICommandHUDBrightnessUp	            	= 746,
	PlaneGear								= 68,
	PlaneFonar								= 71,
	PlaneSalvoOnOff							= 81,
	PlaneChangeWeapon						= 101,
	PlaneChangeWaypoint						= 102,
	PlaneZoomIn								= 103,
	PlaneZoomOut							= 104,
	PlaneBrightnessILS						= 156,
	PlaneLightsOnOff						= 175,
	PlaneDropSnarOnce						= 176,
	PlaneHeadLightOnOff						= 328,
	PlaneModeNAV							= 105,
	PlaneModeBVR							= 106,
	PlaneModeVS								= 107,
	PlaneModeBore							= 108,
	PlaneModeHelmet							= 109,
	PlaneModeFI0							= 110,
	PlaneModeGround							= 111,
	SwitchMasterArm							= 283,
	PlanePickleOn							= 350,
	PlanePickleOff							= 351,
	PlaneWheelBrakeLeftOn					= 961,
	PlaneWheelBrakeLeftOff					= 962,
	PlaneWheelBrakeRightOn	 				= 963,
	PlaneWheelBrakeRightOff					= 964,	
	PlaneMasterCautionOff					= 379,
	PlaneGearUp								= 430,
	PlaneGearDown							= 431,
	PlaneDropSnarOnceOff					= 536,
	PlaneMasterCaution						= 252,
	PlaneScalesReject						= 253,
	PlaneBettyRepeat						= 254,
	ChangeGunRateOfFire						= 280,
	ChangeRippleQuantity					= 281,
	ChangeRippleInterval					= 282,
	ChangeReleaseMode						= 284,
	ChangeRippleIntervalDown				= 308,
	PlaneLaunchPermissionOverride			= 349,
	PlaneCMDDispence						= 364,
	PlaneCMDDispenceOff						= 365,
	PlaneCMDDispenceStop					= 366,
	PlaneCMDDispenceStopOff					= 367,
	PlaneCMDChangeRippleQuantity			= 368,
	PlaneCMDChangeRippleQuantityOff 		= 369,
	PlaneCMDChangeRippleInterval			= 370,
	PlaneCMDChangeRippleIntervalOff 		= 371,
	PlaneCMDChangeBurstAmount				= 372,
	PlaneCMDChangeBurstAmountOff			= 373,
	PlaneCMDCancelCurrentProgram			= 374,
	PlaneCMDCancelCurrentProgramOff 		= 375,
	PlaneCMDChangeBoard						= 376,
	PlaneCMDShowAmountOrProgram				= 377,
	PlaneLaserRangerOnOff					= 392,
	PlaneNightVisionGogglesOnOff			= 438,
	HOTAS_CoolieUp	 						= 539,
	HOTAS_CoolieDown 						= 540,
	HOTAS_CoolieLeft 						= 541,
	HOTAS_CoolieRight						= 542,
	HOTAS_CoolieOff  						= 543,
	HOTAS_TargetManagementSwitchUp	  		= 544,
	HOTAS_TargetManagementSwitchDown  		= 545,
	HOTAS_TargetManagementSwitchLeft  		= 546,
	HOTAS_TargetManagementSwitchRight 		= 547,
	HOTAS_TargetManagementSwitchOff   		= 548,
	HOTAS_DataManagementSwitchUp   			= 549,
	HOTAS_DataManagementSwitchDown 			= 550,
	HOTAS_DataManagementSwitchLeft 			= 551,
	HOTAS_DataManagementSwitchRight			= 552,
	HOTAS_DataManagementSwitchOff  			= 553,
--from iCommand.h
	PlaneSAUAutomatic 						= 58,			
	PlaneSAUHBarometric 					= 59,			
	PlaneSAUHRadio 							= 60,			
	PlaneSAUHorizon							= 61,			
	PlaneAutopilot 							= 62,			
	PlaneAUTOnOff 							= 63,			
	PlaneAUTIncrease 						= 64,			
	PlaneAUTDecrease						= 65,			
	PlaneGear 								= 68,			
	PlaneHook 								= 69,			
	PlanePackWing 							= 70,			
	PlaneFonar 								= 71,			
	PlaneFlaps 								= 72,			
	PlaneAirBrake 							= 73,			
	PlaneWheelBrakeOn 						= 74,			
	PlaneWheelBrakeOff 						= 75,			
	PlaneParachute 							= 76,			
	PlaneDropSnar 							= 77,			
	PlaneWingtipSmokeOnOff 					= 78,			
	PlaneFuelOn 							= 79,			
	PlaneFuelOff							= 80,			
	PlaneSalvoOnOff 						= 81,			
	PiCommandSelecterUplaneJettisonWeapons 	= 82,			
	PlaneEject 								= 83,			
	PlaneFire 								= 84,			
	PlaneFireOff 							= 85,			
	PlaneRadarOnOff 						= 86,			
	PlaneEOSOnOff 							= 87,			
	PlaneRadarLeft 							= 88,			
	PlaneRadarRight 						= 89,			
	PlaneRadarUp							= 90,			
	PlaneRadarDown 							= 91,			
	PlaneRadarCenter 						= 92,			
	PlaneTrimLeft							= 93,			
	PlaneTrimRight 							= 94,			
	PlaneTrimUp 							= 95,			
	PlaneTrimDown 							= 96,			
	PlaneTrimCancel 						= 97,			
	PlaneTrimLeftRudder						= 98,			
	PlaneTrimRightRudder 					= 99,			
	PlaneChangeLock 						= 100,			
	PlaneChangeWeapon 						= 101,			
	PlaneChangeTarget 						= 102,			
	PlaneZoomIn 							= 103,			
	PlaneZoomOut 							= 104,			
	PlaneModeNAV 							= 105,			
	PlaneModeBVR 							= 106,			
	PlaneModeVS 							= 107,			
	PlaneModeBore 							= 108,			
	PlaneModeHelmet 						= 109,			
	PlaneModeFI0 							= 110,			
	PlaneModeGround 						= 111,			
	PlaneModeGrid 							= 112,			
	PlaneModeCannon 						= 113,			
	PlaneDoAndHome 							= 114,			
	PlaneDoAndBack 							= 115,			
	PlaneFormation 							= 116,			
	PlaneJoinUp    							= 117,			
	PlaneAttackMyTarget 					= 118,			
	PlaneCoverMySix 						= 119,			
	PlaneShipTakeOff 						= 120,			
	ActiveJamming 							= 136,
	LandDetailsIncrease 					= 137,			
	LandDetailsDecrease 					= 138,			
	SelecterLeft							= 139,			
	SelecterRight 							= 140,			
	SelecterUp  							= 141,			
	SelecterDown 							= 142,			
	RefusalTWS 								= 143,			
	PlaneResetMasterWarning 				= 144,
	PlaneFlapsOn 							= 145,
	PlaneFlapsOff 							= 146,
	PlaneAirBrakeOn 						= 147,
	PlaneAirBrakeOff 						= 148,
	PlaneAirRefuel 							= 155,			
	BrightnessILS 							= 156,			
	PlaneAUTIncreaseLeft 					= 161,
	PlaneAUTDecreaseLeft 					= 162,
	PlaneAUTIncreaseRight 					= 163,
	PlaneAUTDecreaseRight 					= 164,
	PlaneLightsOnOff 						= 175,		
	PlaneDropSnarOnce 						= 176,		
	PlaneJettisonFuelTanks 					= 178,		
	PlaneWingmenCommand 					= 179,		
	PlaneDown 								= 186,		
	PlaneUp 								= 187,
	PlaneLeft 								= 188,
	PlaneRight 								= 189,
    PlaneUpStart 							= 193,
    PlaneUpStop 							= 194,
    PlaneDownStart							= 195,
    PlaneDownStop 							= 196,
    PlaneLeftStart 							= 197,
    PlaneLeftStop 							= 198,
    PlaneRightStart 						= 199,
    PlaneRightStop 							= 200,
    PlaneLeftRudderStart 					= 201,
    PlaneLeftRudderStop 					= 202,
    PlaneRightRudderStart 					= 203,
    PlaneRightRudderStop 					= 204,
    PlaneTrimStop 							= 215,
    SelecterUpRight 						= 226,
    SelecterDownRight 						= 227,
    SelecterDownLeft 						= 228,
    SelecterUpLeft 							= 229,
    SelecterStop 							= 230,
    PlaneRadarUpRight 						= 231,
    PlaneRadarDownRight 					= 232,
    PlaneRadarDownLeft 						= 233,
    PlaneRadarUpLeft 						= 234,
    PlaneRadarStop 							= 235,
	PlaneHUDFilterOnOff 					= 247,			
	PlaneMasterCaution 						= 252,			
	PlaneScalesReject						= 253,			
	PlaneBettyRepeat 						= 254,			
	ThreatMissilePadlock 					= 258,
	AllMissilePadlock 						= 259,
	DecreaseRadarScanArea 					= 262,
    IncreaseRadarScanArea 					= 263,
	AWACSHomeBearing 						= 267,
	AWACSTankerBearing 						= 268,
	AWACSBanditBearing 						= 269,
    AWACSDeclare 							= 270,
    EasyRadarOnOff 							= 271,
    AutoLockOnNearestAircraft 				= 272,
    AutoLockOnCenterAircraft 				= 273,
    AutoLockOnNextAircraft 					= 274,
    AutoLockOnPreviousAircraft 				= 275,
    AutoLockOnNearestSurfaceTarget 			= 276,
    AutoLockOnCenterSurfaceTarget 			= 277,
    AutoLockOnNextSurfaceTarget 			= 278,
    AutoLockOnPreviousSurfaceTarget 		= 279,
	ChangeGunRateOfFire 					= 280,
	ChangeRippleQuantity 					= 281,
	ChangeRippleInterval 					= 282,
	SwitchMasterArm 						= 283,
	ChangeReleaseMode 						= 284,
    PlaneRadarChangeMode 					= 285,
	ChangeRWRMode 							= 286,
	FlightClockReset 						= 288,
	PlaneCockpitIllumination 				= 300,
	ChangeRippleIntervalDown 				= 308,	
	EnginesStart 							= 309,	
	EnginesStop 							= 310,	
	LeftEngineStart 						= 311,	
	RightEngineStart 						= 312,	
	LeftEngineStop							= 313,	
	RightEngineStop 						= 314,	
	PowerOnOff 								= 315,	
	PowerGeneratorLeft 						= 711,
    PowerGeneratorRight 					= 712,
    BatteryPower 							= 1073,  
	AltimeterPressureIncrease 				= 316,	
	AltimeterPressureDecrease 				= 317,	
	AltimeterPressureStop 					= 318,
	PlaneHeadLightOnOff 					= 328,	
	PlaneLockPadlock 						= 329,	
	PlaneUnlockPadlock 						= 330,	
	PlaneLaunchPermissionOverride			= 349,	
	PlanePickleOn 							= 350,	
	PlanePickleOff 							= 351,
	PlaneDropFlareOnce 						= 357,	
	PlaneDropChaffOnce 						= 358,	
	PlaneCMDDispence 						= 364,	
	PlaneCMDDispenceOff 					= 365,
	PlaneCMDDispenceStop 					= 366,	
	PlaneCMDDispenceStopOff 				= 367,
	PlaneCMDChangeRippleQuantity 			= 368,	
	PlaneCMDChangeRippleInterval 			= 370,	
	PlaneCMDChangeBurstAmount 				= 372,	
	PlaneCMDChangeBurstAmountOff 			= 373,
	PlaneCMDCancelCurrentProgram 			= 374,	
	PlaneCMDChangeBoard 					= 376,	
	PlaneCMDShowAmountOrProgram 			= 377,	
	PlaneCancelWeaponsDelivery 				= 378,	
	PlaneMasterCautionOff 					= 379,
	PlaneStabTangBank 						= 386,	
	PlaneStabHbarBank 						= 387,	
	PlaneStabHorizon 						= 388,	
	PlaneStabHbar 							= 389,	
	PlaneStabHrad 							= 390,	
	ActiveIRJamming 						= 391,	
	PlaneLaserRangerOnOff 					= 392, 	
	PlaneNightTVOnOff						= 393,   
	PlaneChangeRadarPRF 					= 394,   
	PlaneStabCancel 						= 408,	
	PlaneThreatWarnSoundVolumeDown 			= 409,	
	PlaneThreatWarnSoundVolumeUp 			= 410,	
	ViewLaserOnOff 							= 411,
	PlaneIncreaseBase_Distance 				= 412,     
	PlaneDecreaseBase_Distance				= 413,     
	PlaneStopBase_Distance 					= 414,
	PlaneAutopilotOverrideOn 				= 427,
	PlaneAutopilotOverrideOff 				= 428,
	PlaneRouteAutopilot 					= 429,
	PlaneGearUp 							= 430,
	PlaneGearDown 							= 431,
	ViewNightVisionGogglesOn 				= 438,
	PlaneDesignate_CageOn 					= 439,
	PlaneDesignate_CageOff 					= 440,
	PlaneDesignate_CageOn_vertical 			= 441,
	PlaneDesignate_CageOn_horizontal 		= 442,
	PlaneDLK_Target1 						= 443,
	PlaneDLK_Target2 						= 444,
	PlaneDLK_Target3 						= 445,
	PlaneDLK_RefPoint 						= 446,
	PlaneDLK_Wingman1 						= 447,
	PlaneDLK_Wingman2 						= 448,
	PlaneDLK_Wingman3 						= 449,
	PlaneDLK_Wingman4 						= 450,
	PlaneDLK_All 							= 451,
	PlaneDLK_Erase 							= 452,
	PlaneDLK_Ingress 						= 453,
	PlaneDLK_SendMemory 					= 454,
	PlaneNavChangePanelModeRight 			= 455,
	PlaneNavChangePanelModeLeft 			= 456,
	PlaneNavSetFixtakingMode 				= 457,
	PlaneNav_DLK_OnOff 						= 458,
	PlaneNav_PB1 							= 459,
	PlaneNav_PB2 							= 460,
	PlaneNav_PB3 							= 461,
	PlaneNav_PB4 							= 462,
	PlaneNav_PB5 							= 463,
	PlaneNav_PB6 							= 464,
	PlaneNav_PB7 							= 465,
	PlaneNav_PB8 							= 466,
	PlaneNav_PB9 							= 467,
	PlaneNav_PB0 							= 468,
	PlaneNav_Steerpoints 					= 469,
	PlaneNav_INU_realign 					= 470,
	PlaneNav_POS_corrMode 					= 471,
	PlaneNav_INU_precise_align 				= 472,
	PlaneNav_Airfields 						= 473,
	PlaneNav_INU_normal_align  				= 474,
	PlaneNav_Targets 						= 475,
	PlaneNav_Enter 							= 476,
	PlaneNav_Cancel 						= 477,
	PlaneNav_POS_init 						= 478,
	PlaneNav_SelfCoord 						= 479,
	PlaneNav_CourseTimeRange 				= 480,
	PlaneNav_Wind 							= 481,
	PlaneNav_THeadingTimeRangeF 			= 482,
	PlaneNav_BearingRangeT 					= 483,
	PlaneCockpitIlluminationPanels 			= 493,
	PlaneCockpitIlluminationGauges 			= 494,
	Plane_RouteMode 						= 506,
	Plane_DescentMode 						= 507,
	Plane_DescentModeOff 					= 508,
	Plane_SpotLight_left 					= 511,
	Plane_SpotLight_right 					= 512,
	Plane_SpotLight_up						= 513,
	Plane_SpotLight_down 					= 514,
	Plane_SpotLight_stop 					= 515,
	PlaneRotorTipLights 					= 516,
	Plane_SpotSelect_switch 				= 517,
	PlaneAntiCollisionLights 				= 518,
	PlaneNavLights_CodeModeOn 				= 519,
	PlaneNavLights_CodeModeOff				= 520,
	PlaneFormationLights 					= 521,
	Plane_EngageAirDefenses 				= 522,
	Plane_EngageGroundTargets				= 523,
	Plane_AutomaticTracking_Gunsight_switch = 524,
	Plane_AutomaticTurn 					= 526,
	Plane_GroundMovingTarget 				= 527,
	Plane_AirborneTarget 					= 528,
	Plane_HeadOnAspect 						= 529,
	Plane_ChangeDeliveryMode_right 			= 530,
	Plane_ChangeDeliveryMode_left 			= 531,
	Plane_WeaponMode_Manual_Auto 			= 532,
	Plane_WeaponMode_switch 				= 533,
	Plane_AmmoTypeSelect 					= 534,
	Plane_FireRate 							= 535,
	PlaneDropSnarOnceOff 					= 536,
	HelicopterHover 						= 537,
	AutopilotEmergOFF 						= 538,
	Plane_HOTAS_CoolieUp 					= 539,
	Plane_HOTAS_CoolieDown 					= 540,
	Plane_HOTAS_CoolieLeft 					= 541,
	Plane_HOTAS_CoolieRight 				= 542,
	Plane_HOTAS_CoolieOff 					= 543,
	Plane_HOTAS_TargetManagementSwitchUp 	= 544,
	Plane_HOTAS_TargetManagementSwitchDown 	= 545,
	Plane_HOTAS_TargetManagementSwitchLeft 	= 546,
	Plane_HOTAS_TargetManagementSwitchRight = 547,
	Plane_HOTAS_TargetManagementSwitchOff 	= 548,
	Plane_HOTAS_DataManagementSwitchUp 		= 549,
	Plane_HOTAS_DataManagementSwitchDown 	= 550,
	Plane_HOTAS_DataManagementSwitchLeft 	= 551,
	Plane_HOTAS_DataManagementSwitchRight 	= 552,
	Plane_HOTAS_DataManagementSwitchOff		= 553,
	Plane_HOTAS_TriggerSecondStage 			= 554,
	Plane_HOTAS_TriggerFirstStage 			= 555,
	Plane_HOTAS_CMS_Up 						= 556,
	Plane_HOTAS_CMS_Down 					= 557,
	Plane_HOTAS_CMS_Left 					= 558,
	Plane_HOTAS_CMS_Right 					= 559,
	Plane_HOTAS_CMS_Off 					= 560,
	Plane_HOTAS_MasterModeControlButton 	= 561,
	Plane_HOTAS_NoseWheelSteeringButton 	= 562,
	Plane_HOTAS_NoseWheelSteeringButtonOff 	= 606,
	Plane_HOTAS_BoatSwitchForward 			= 563,
	Plane_HOTAS_BoatSwitchAft 				= 564,
	Plane_HOTAS_BoatSwitchCenter 			= 565,
	Plane_HOTAS_ChinaHatForward 			= 566,
	Plane_HOTAS_ChinaHatAft 				= 567,
	Plane_HOTAS_ChinaHatOff 				= 589,
	Plane_HOTAS_PinkySwitchForward 			= 568,
	Plane_HOTAS_PinkySwitchAft 				= 569,
	Plane_HOTAS_PinkySwitchCenter 			= 570,
	Plane_HOTAS_LeftThrottleButton 			= 571,
	Plane_HOTAS_MIC_SwitchUp 				= 572,
	Plane_HOTAS_MIC_SwitchDown 				= 573,
	Plane_HOTAS_MIC_SwitchLeft 				= 574,
	Plane_HOTAS_MIC_SwitchRight 			= 575,
	Plane_HOTAS_MIC_SwitchOff 				= 576,
	Plane_HOTAS_SpeedBrakeSwitchForward 	= 577,
	Plane_HOTAS_SpeedBrakeSwitchAft 		= 578,
	Plane_HOTAS_SpeedBrakeSwitchCenter 		= 579,
	Plane_HOTAS_MasterModeControlButtonUP 	= 633,
	Plane_HOTAS_TDC_depress_on  			= 634,
	Plane_HOTAS_TDC_depress_off 			= 635,
	Plane_HOTAS_TriggerSecondStage_Off 		= 638,
	Plane_HOTAS_TriggerFirstStage_Off  		= 639,
	Plane_HOTAS_CMS_Zaxis 					= 1041,
	Plane_HOTAS_CMS_Zaxis_Off 				= 1042,
	Plane_HOTAS_BoatSwitchOff				= 822,
	Plane_HOTAS_BoatSwitchForwardMomentary 	= 823,
	Plane_HOTAS_BoatSwitchAftMomentary 		= 824,
	Plane_CockpitShowPilotOnOff				= 835,
	Plane_HOTAS_LeftThrottleButton_Off 		= 1557,
	PlaneRadarHorizontal 	   				= 2025,
	PlaneRadarVertical 		   				= 2026,
	PlaneRadarHorizontalAbs    				= 2027,
	PlaneRadarVerticalAbs 	   				= 2028,
	PlaneMFDZoom 		       				= 2029,
	PlaneMFDZoomAbs			   				= 2030,
	PlaneSelecterHorizontal    				= 2031,
	PlaneSelecterVertical 	   				= 2032,
	PlaneSelecterHorizontalAbs 				= 2033,
	PlaneSelecterVerticalAbs   				= 2034,
	PlaneBase_Distance 		   				= 2040,
	PlaneBase_DistanceAbs 	   				= 2041,
	LampsControl							= 762,
	LampsControl_up							= 800,
-------------------------------------------------------
--Left Console Panel
------------------------------------------------------- 

-------------------------------------------------------
--Left Auxiliary Console
-------------------------------------------------------

-------------------------------------------------------
--UCP (Upfront Control Panel)
-------------------------------------------------------
	UCP_MENU								= __custom_counter(),
	UCP_1									= __custom_counter(),
	UCP_2									= __custom_counter(),
	UCP_3									= __custom_counter(),
	UCP_DAT									= __custom_counter(),
	UCP_SHIFT								= __custom_counter(),
	UCP_4									= __custom_counter(),
	UCP_5									= __custom_counter(),
	UCP_6									= __custom_counter(),
	UCP_0									= __custom_counter(),
	UCP_AMFM_ENT							= __custom_counter(),
	UCP_7									= __custom_counter(),
	UCP_8									= __custom_counter(),
	UCP_9									= __custom_counter(),
	UCP_L									= __custom_counter(),
	UCP_CLR									= __custom_counter(),
	UCP_Brightness							= __custom_counter(),

-------------------------------------------------------
--Instrument Panel
-------------------------------------------------------
--Left control panel
	LCP_X	      							= __custom_counter(),
	LCP_SYS       							= __custom_counter(),
	LCP_TAC       							= __custom_counter(),
	LCP_IFF       							= __custom_counter(),
	LCP_COM       							= __custom_counter(),
	LCP_SK01      							= __custom_counter(), --upper left dashed lcp softkey
	LCP_SK02      							= __custom_counter(),
	LCP_SK03      							= __custom_counter(),
	LCP_SK04      							= __custom_counter(),
	LCP_SK05      							= __custom_counter(),
	LCP_SK06      							= __custom_counter(),
	LCP_SK07      							= __custom_counter(),--middle bottom dashed lcp softkey
	LCP_SK08      							= __custom_counter(),
	LCP_SK09      							= __custom_counter(),
	LCP_SK10      							= __custom_counter(),
	LCP_SK11      							= __custom_counter(),
	LCP_SK12      							= __custom_counter(),
	LCP_SK13      							= __custom_counter(),--upper right dashed lcp softkey
	LCP_Brightness							= __custom_counter(),
	LCP_Contrast  							= __custom_counter(),
	LCP_1                  					= __custom_counter(),
	LCP_2                  					= __custom_counter(),
	LCP_3                  					= __custom_counter(),
	LCP_4                  					= __custom_counter(),
	LCP_5                  					= __custom_counter(),
	LCP_6                  					= __custom_counter(),
	LCP_7                  					= __custom_counter(),
	LCP_8                  					= __custom_counter(),
	LCP_9                  					= __custom_counter(),
	LCP_0                  					= __custom_counter(),
	LCP_ENT                					= __custom_counter(),
	LCP_CLR                					= __custom_counter(),
-------------------------------------------------------
--LD
-------------------------------------------------------
	LDSK_1									= __custom_counter(),
	LDSK_2									= __custom_counter(),
	LDSK_3									= __custom_counter(),
	LDSK_4									= __custom_counter(),
	LDSK_5									= __custom_counter(),
	LDSK_6									= __custom_counter(),
	LDSK_7									= __custom_counter(),
	LDSK_8									= __custom_counter(),
	LDSK_9									= __custom_counter(),
	LDSK_10									= __custom_counter(),
	LDSK_11									= __custom_counter(),
	LDSK_12									= __custom_counter(),
	LDSK_13									= __custom_counter(),
	LDSK_14									= __custom_counter(),
	LDSK_15									= __custom_counter(),
	LDSK_16									= __custom_counter(),
	LDSK_17									= __custom_counter(),
	LDSK_18									= __custom_counter(),
	LDSK_19									= __custom_counter(),
	LDSK_20									= __custom_counter(),
--Brightnessness                                 
	LD_Brightness_Up						= __custom_counter(),
	LD_Brightness_Down						= __custom_counter(),
--Contrast                                  
	LD_Contrast_Up							= __custom_counter(),
	LD_Contrast_Down						= __custom_counter(),
-------------------------------------------------------
--CD
-------------------------------------------------------
	CDSK_1									= __custom_counter(),
	CDSK_2									= __custom_counter(),
	CDSK_3									= __custom_counter(),
	CDSK_4									= __custom_counter(),
	CDSK_5									= __custom_counter(),
	CDSK_6									= __custom_counter(),
	CDSK_7									= __custom_counter(),
	CDSK_8									= __custom_counter(),
	CDSK_9									= __custom_counter(),
	CDSK_10									= __custom_counter(),
	CDSK_11									= __custom_counter(),
	CDSK_12									= __custom_counter(),
	CDSK_13									= __custom_counter(),
	CDSK_14									= __custom_counter(),
	CDSK_15									= __custom_counter(),
	CDSK_16									= __custom_counter(),
	CDSK_17									= __custom_counter(),
	CDSK_18									= __custom_counter(),
	CDSK_19									= __custom_counter(),
	CDSK_20									= __custom_counter(),
--Brightnessness                                 
	CD_Brightness_Up						= __custom_counter(),
	CD_Brightness_Down						= __custom_counter(),
--Contrast                                  
	CD_Contrast_Up							= __custom_counter(),
	CD_Contrast_Down						= __custom_counter(),	
-------------------------------------------------------
--RD 
-------------------------------------------------------
	CDSK_1									= __custom_counter(),
	RDSK_2									= __custom_counter(),
	RDSK_3									= __custom_counter(),
	RDSK_4									= __custom_counter(),
	RDSK_5									= __custom_counter(),
	RDSK_6									= __custom_counter(),
	RDSK_7									= __custom_counter(),
	RDSK_8									= __custom_counter(),
	RDSK_9									= __custom_counter(),
	RDSK_10									= __custom_counter(),
	RDSK_11									= __custom_counter(),
	RDSK_12									= __custom_counter(),
	RDSK_13									= __custom_counter(),
	RDSK_14									= __custom_counter(),
	RDSK_15									= __custom_counter(),
	RDSK_16									= __custom_counter(),
	RDSK_17									= __custom_counter(),
	RDSK_18									= __custom_counter(),
	RDSK_19									= __custom_counter(),
	RDSK_20									= __custom_counter(),
--Brightnessness                                 
	RD_Brightness_Up						= __custom_counter(),
	RD_Brightness_Down						= __custom_counter(),
--Contrast                                  
	RD_Contrast_Up							= __custom_counter(),
	RD_Contrast_Down						= __custom_counter(),	
-------------------------------------------------------
--Right Auxiliary Console
-------------------------------------------------------

-------------------------------------------------------
--Right Console Panel
-------------------------------------------------------
-------------------------------------------------------
--HOTAS
-------------------------------------------------------

-------------------------------------------------------
--Ejection Seat
-------------------------------------------------------

	

-------------------------------------------------------
--Other
-------------------------------------------------------	
}
-------------------------------------------------------
--DEVICE COMMANDS
-------------------------------------------------------
device_commands =
{
	
	 BrakesON      							= 10038,
	 BrakesOFF     							= 10039,
	 L_BRAKE       							= 10056,
	 R_BRAKE       							= 10057,
	 B_BRAKE       							= 10058,
	 Brakes        							= 10023,
	 P_BRAKE	   							= 10059,
	 LANDING_MODE  							= 10060,
	 PITCHBW_AXIS  							= 10061, 
	 ROLLBW_AXIS   							= 10062, 
	 YAWBW_AXIS    							= 10063, 
	 AUTOTHROTTLE  							= 10064,
	 ATAOA_1214	   							= 10065,
	 THROTTLE_AXIS 							= 10066,
}
start_command   = 3200
local __count = start_command-1
local function __counter()
	__count = __count + 1
	return __count
end
device_commands =
{
-------------------------------------------------------
--FC3 Commands
------------------------------------------------------- 	
	COM1                                    = __counter(),
	COM2                                    = __counter(),
	AP_ATT									= __counter(),
	AP_ALT									= __counter(),
	AP_RSET									= __counter(),
	AP_OFF									= __counter(),
	NAV_NEXT                                = __counter(),
	NAV_PREV                                = __counter(),
	RDR_PRF                                 = __counter(),
	RDR_PWR                                 = __counter(),
	RDR_MODE                                = __counter(),
	RDR_IN                                  = __counter(),
	RDR_OUT                                 = __counter(),
	RDR_UP									= __counter(),
	RDR_DOWN								= __counter(),
	RDR_LEFT								= __counter(),
	RDR_RIGHT								= __counter(),
	EO										= __counter(),
	Seat_Ajust								= __counter(),
	T1										= __counter(),
	T2										= __counter(),
	T3										= __counter(),
	T4										= __counter(),
	T5										= __counter(),
	T6										= __counter(),
	MIRROR									= __counter(),
	LKneeboardDraw							= __counter(),
	RKneeboardDraw							= __counter(),
	JoystickDraw							= __counter(),
	MAP										= __counter(),
	HMD_LIGHT								= __counter(),--2090
	ATT_LIGHT								= __counter(),--2078
	ALT_LIGTH								= __counter(),--2077
	MAN_LIGTH								= __counter(),--2079
	SPEEDBRAKEIND							= __counter(),--2036(-1 off 0 on)
-------------------------------------------------------
--Left Console Panel
------------------------------------------------------- 
--Left control panel
	LCP_X	      							= __counter(),
	LCP_SYS       							= __counter(),
	LCP_TAC       							= __counter(),
	LCP_IFF       							= __counter(),
	LCP_COM       							= __counter(),
	LCP_SK01      							= __counter(),  --upper left dashed lcp softkey
	LCP_SK02      							= __counter(),
	LCP_SK03      							= __counter(),
	LCP_SK04      							= __counter(),
	LCP_SK05      							= __counter(),
	LCP_SK06      							= __counter(),
	LCP_SK07      							= __counter(),	--middle bottom dashed lcp softkey
	LCP_SK08      							= __counter(),
	LCP_SK09      							= __counter(),
	LCP_SK10      							= __counter(),
	LCP_SK11      							= __counter(),
	LCP_SK12      							= __counter(),
	LCP_SK13      							= __counter(),	--upper right dashed lcp softkey
	LCP_Brightness							= __counter(),
	LCP_Contrast  							= __counter(),
	LCP_1                  					= __counter(),
	LCP_2                  					= __counter(),
	LCP_3                  					= __counter(),
	LCP_4                  					= __counter(),
	LCP_5                  					= __counter(),
	LCP_6                  					= __counter(),
	LCP_7                  					= __counter(),
	LCP_8                  					= __counter(),
	LCP_9                  					= __counter(),
	LCP_0                  					= __counter(),
	LCP_ENT                					= __counter(),
	LCP_CLR                					= __counter(),
--Target acquisition panel
	TAP_ERAZ_cover							= __counter(),
	TAP_ERAZ								= __counter(),	
	TAP_T2									= __counter(),
	TAP_T3									= __counter(),
	TAP_INIT								= __counter(),
	TAP_RDR									= __counter(),
	TAP_ECM									= __counter(),
	TAP_CMDS								= __counter(),
	TAP_T6									= __counter(),
	TAP_T9									= __counter(),
	TAP_XPCR								= __counter(),
	TAP_IQ									= __counter(),
	TAP_INT									= __counter(),
	TAP_T13									= __counter(),
	TAP_T14									= __counter(),
	TAP_IFFEMGY_OFF							= __counter(),
	TAP_FREQ							    = __counter(),
	TAP_CONT							    = __counter(),
	TAP_THRSHOLD							= __counter(),
	TAP_GAIN								= __counter(),
-------------------------------------------------------
--Left Auxiliary Console
-------------------------------------------------------
    LandingGearLever            			= __counter(),
	Start                       			= __counter(),
	Main                        			= __counter(),
	APU                         			= __counter(),
	WeaponJettison              			= __counter(),
	WeaponJettisonCover						= __counter(),
	TankJettison                			= __counter(),
	TankJettisonCover						= __counter(),
	Fuel                        			= __counter(),
	FuelCover								= __counter(),
	ParkingBrake                			= __counter(),
	SeatUpDown                     			= __counter(),
	CanopyJettison              			= __counter(),
	CanopyLever                 			= __counter(),
    Mass               						= __counter(),	
	ThrottleStop       						= __counter(),
	MasterCaution							= __counter(),
	CovertLights							= __counter(),
	FormationLights							= __counter(),
	FormFlashLights							= __counter(),
	LandingTaxiLights           			= __counter(),
	NavigationLights            			= __counter(),
	AntiCollisionLights         			= __counter(),	
	GearLights                  			= __counter(),
	FloodLight                  			= __counter(),
	IndicatorLight							= __counter(),
	BackLight								= __counter(),
	IN_Knob			 						= __counter(),--Work
	SeatArm		                  			= __counter(),
	DTU	                                    = __counter(),
	TriggerSafe                             = __counter(),
	CannonMode                             	= __counter(),	
	AARProbeCover                           = __counter(),
	AARProbe                                = __counter(),
	EmergencyJettisonCover                  = __counter(),
	EmergencyJettison                       = __counter(),
	Compartment								= __counter(),
-------------------------------------------------------
--UCP (Upfront Control Panel)
-------------------------------------------------------
	UCP_MENU								= __counter(),
	UCP_1									= __counter(),
	UCP_2									= __counter(),
	UCP_3									= __counter(),
	UCP_DAT									= __counter(),
	UCP_SHIFT								= __counter(),
	UCP_4									= __counter(),
	UCP_5									= __counter(),
	UCP_6									= __counter(),
	UCP_0									= __counter(),
	UCP_AMFM_ENT							= __counter(),
	UCP_7									= __counter(),
	UCP_8									= __counter(),
	UCP_9									= __counter(),
	UCP_CLR									= __counter(),
	UCP_L									= __counter(),
	UCP_Brightness							= __counter(),
-------------------------------------------------------
--Instrument Panel
-------------------------------------------------------
--HMD On off
	HMDTOGGLE								= __counter(),	
--HUD	
	HUD_Brightness							= __counter(),
-------------------------------------------------------
--LD
-------------------------------------------------------
	LDSK_1									= __counter(),
	LDSK_2									= __counter(),
	LDSK_3									= __counter(),
	LDSK_4									= __counter(),
	LDSK_5									= __counter(),
	LDSK_6									= __counter(),
	LDSK_7									= __counter(),
	LDSK_8									= __counter(),
	LDSK_9									= __counter(),
	LDSK_10									= __counter(),
	LDSK_11									= __counter(),
	LDSK_12									= __counter(),
	LDSK_13									= __counter(),
	LDSK_14									= __counter(),
	LDSK_15									= __counter(),
	LDSK_16									= __counter(),
	LDSK_17									= __counter(),
	LDSK_18									= __counter(),
	LDSK_19									= __counter(),
	LDSK_20									= __counter(),
--Brightnessness                          
	LD_Brightness_Up						= __counter(),
	LD_Brightness_Down						= __counter(),
--Contrast                             
	LD_Contrast_Up							= __counter(),
	LD_Contrast_Down						= __counter(),	
-------------------------------------------------------
--CD
-------------------------------------------------------
	CDSK_1									= __counter(),
	CDSK_2									= __counter(),
	CDSK_3									= __counter(),
	CDSK_4									= __counter(),
	CDSK_5									= __counter(),
	CDSK_6									= __counter(),
	CDSK_7									= __counter(),
	CDSK_8									= __counter(),
	CDSK_9									= __counter(),
	CDSK_10									= __counter(),
	CDSK_11									= __counter(),
	CDSK_12									= __counter(),
	CDSK_13									= __counter(),
	CDSK_14									= __counter(),
	CDSK_15									= __counter(),
	CDSK_16									= __counter(),
	CDSK_17									= __counter(),
	CDSK_18									= __counter(),
	CDSK_19									= __counter(),
	CDSK_20									= __counter(),
--Brightnessness                            
	CD_Brightness_Up						= __counter(),
	CD_Brightness_Down						= __counter(),
--Contrast                                 
	CD_Contrast_Up							= __counter(),
	CD_Contrast_Down						= __counter(),
-------------------------------------------------------
--RD
-------------------------------------------------------
	RDSK_1									= __counter(),
	RDSK_2									= __counter(),
	RDSK_3									= __counter(),
	RDSK_4									= __counter(),
	RDSK_5									= __counter(),
	RDSK_6									= __counter(),
	RDSK_7									= __counter(),
	RDSK_8									= __counter(),
	RDSK_9									= __counter(),
	RDSK_10									= __counter(),
	RDSK_11									= __counter(),
	RDSK_12									= __counter(),
	RDSK_13									= __counter(),
	RDSK_14									= __counter(),
	RDSK_15									= __counter(),
	RDSK_16									= __counter(),
	RDSK_17									= __counter(),
	RDSK_18									= __counter(),
	RDSK_19									= __counter(),
	RDSK_20									= __counter(),
--Brightnessness                            
	RD_Brightness_Up						= __counter(),	
	RD_Brightness_Down						= __counter(),	
--Contrast                                 	
	RD_Contrast_Up							= __counter(),	
	RD_Contrast_Down						= __counter(),	
-------------------------------------------------------
--Right Auxiliary Console
-------------------------------------------------------

-------------------------------------------------------
--Right Console Panel
-------------------------------------------------------
--Audio control panel
	ACP_1                  					= __counter(),
	ACP_2                  					= __counter(),
	ACP_3                  					= __counter(),
	ACP_4                  					= __counter(),
	ACP_5                  					= __counter(),
	ACP_6                  					= __counter(),
	ACP_7                  					= __counter(),
	ACP_8                  					= __counter(),
	ACP_9                  					= __counter(),
    ACP_0                  					= __counter(),
    ACP_AMFM_ENT                  			= __counter(),
	ACP_CLR_MUTE                  			= __counter(),
	ACP_COM1_EDIT                 			= __counter(),
	ACP_COM2_EDIT                 			= __counter(),
	ACP_AUX_EDIT                  			= __counter(),
	ACP_TELE_OFF                  			= __counter(),
	ACP_PTT1                  				= __counter(),
	ACP_PTT2                  				= __counter(),
	ACP_VOL                  				= __counter(),
	ACP_MENU                 				= __counter(),
-------------------------------------------------------
--HOTAS
-------------------------------------------------------

-------------------------------------------------------
--Ejection Seat
-------------------------------------------------------
	SeatEject 	                 			= __counter(),	
-------------------------------------------------------
--Others
-------------------------------------------------------
}