lessons = 
{
	{
        ["file"] = "JAS39 - Training - M01 Cold Start (by Rudel_chw).miz",
        ["name"] = _("M01 - Cold Start at Marianas. (JAS-39C A/A and A/G)"),
        ["description"] = _("On this Mission, we will learn how to do a Cold Start on the Saab JAS-39C Gripen, following the Procedure indicated by this Mod’s developers.\n\nContents:\n\nThe Cold Start Procedure includes the following Sections:\n\n- Before Engine Start\n\n- Engine Start.\n\n- Before Taxi.\n\nThe approximate mission time is 10 minutes.\n\nThis training series is set on the Marianas Map, taking advantage of a cooperation training program established recently between the USAF and the Flygvapnet, which allows our pilots to experience a very different climate away from home."),
    },
	{
        ["file"] = "JAS39 - Training - M02 Taxi & Takeoff (by Rudel_chw).miz",
        ["name"] = _("M02 - Taxi, Take-Off & Initial Climb. (JAS-39C A/A and A/G)"),
        ["description"] = _("On this Mission, we will learn how to perform a Taxi and a Take-Off on the Saab JAS-39C Gripen, following the Procedure indicated by this Mod’s developers.\n\nContents:\n\nThe Checklist includes the following Sections:\n\n- Before Taxi.\n\n- Taxi.\n\n- Before Take-Off.\n\n- Take-Off.\n\n- Initial Climb.\n\nThe approximate mission time is 10 minutes, and ends when you have climbed above 5,000 feet.\n\nThis training series is set on the Marianas Map, taking advantage of a cooperation training program established recently between the USAF and the Flygvapnet, which allows our pilots to experience a very different climate away from home."),
    },
	{
        ["file"] = "JAS39 - Training - M04 VFR Landing (by Rudel_chw).miz",
        ["name"] = _("M04 - VFR (Visual Flight Rules) Landing at Marianas. (JAS-39C A/A and A/G)"),
        ["description"] = _("On this Mission, we will learn how to perform a Visual Landing at Saipan Intl. airbase with the Saab JAS-39C Gripen, following the Procedures provided by this Mod’s developers.\n\nContents:\n\nThe Checklist includes the following Sections:\n\n- Approach the Airbase.\n\n- Final Approach.\n\n- Taxi to Ramp.\n\n- Shutdown (optional).\n\nThe approximate mission time is 10-15 minutes, depending on whether you perform the Shutdown Procedure or not.\n\nThis training series is set on the Marianas Map, taking advantage of a cooperation training program established recently between the USAF and the Flygvapnet, which allows our pilots to experience a very different climate away from home."),
    },
{
        ["file"] = "JAS39 - Training - M10 Gun Strafing (by Rudel_chw).miz",
        ["name"] = _("M10 - Gun Strafing. (JAS-39C A/G)"),
        ["description"] = _("This Training Mission will be our first weapons employment lesson, where we will be using the Saab JAS-39C Gripen’s Cannon to strafe at gunnery targets setup at Tinian’s North Field Weapons Range.\n\nGround observers will record accuracy statistics, so that you can measure your marksmanship and use this mission not only as training, but also to practice and improve your shooting precision.\n\nThe Mission provides two aircraft slots to choose from:\n\n-	Full Mission: Starts with the aircraft on the Ramp of Saipan airbase, already started. You must Taxi, Take-Off and Navigate to Tinian’s Weapons Range.\n\n-	Air Start: You start already on the air, heading towards the Range.\n\nBefore taking one of these aircraft Slots, select the Spectators Role, to give the mission time to activate the Weapons Range script.\n\nThe return to base after spending all the gun ammunition, is optional, as is the final Shutdown. The approximate mission time is 20-30 minutes, depending on the slot chosen and whether you return to base or not.\n\nThe mission requires your DCS to have the 476th Target Range Objects user Mod installed."),
    },
{
        ["file"] = "JAS39 - Training - M11 Unguided Rockets (by Rudel_chw).miz",
        ["name"] = _("M11 - Unguided Rockets. (JAS-39C A/G)"),
        ["description"] = _("On this Training Mission we will learn the use of unguided Rockets on the Saab JAS-39C, firing to a Rocket Target Circle setup at Tinian’s North Field Weapons Range.\n\nGround observers will record accuracy statistics, so that you can measure your precision and use this mission not only as training, but also to practice and improve your shooting markmanship.\n\nThe Mission provides two aircraft slots to choose from:\n\n- Full Mission: Starts with the aircraft on the Ramp of Saipan airbase, already started. You must Taxi, Take-Off and Navigate to Tinian’s Weapons Range.\n\n- Air Start: You start already on the air, heading towards the Range.\n\nBefore taking one of these aircraft Slots, select the Spectators Role, to give the mission time to activate the Weapons Range script.\n\nThe return to base after launching all Rockets, is optional, as is the final Shutdown. The approximate mission time is 20-30 minutes, depending on the slot chosen and whether you return to base or not.\n\nThe mission requires your DCS to have the 476th Target Range Objects user Mod installed."),
    },	
{
        ["file"] = "JAS39 - Training - M12 Iron Bombs (by Rudel_chw).miz",
        ["name"] = _("M12 - CCIP Iron Bombs. (JAS-39C A/G)"),
        ["description"] = _("On this Training Mission we will learn the use of Iron Bombs on the Saab JAS-39C, dropping them with precision, on a Bombing Target Circle setup at Tinian’s North Field Weapons Range.\n\nWe will try two different size of bombs, dropping four of each on two passes over the Target Range:\n\n- Mk 82: 500 lb general purpose bomb.\n\n- Mk 83: 1,000 lb version of the same bomb.\n\nThe Mission provides two aircraft slots to choose from:\n\n-	Full Mission: Starts with the aircraft on the Ramp of Saipan airbase, already started. You must Taxi, Take-Off and Navigate to Tinian’s Weapons Range.\n\n- Air Start: You start already on the air, heading towards the Range.\n\nBefore taking one of these aircraft Slots, select the Spectators Role, to give the mission time to activate the Weapons Range script.\n\nThe return to base after launching all bombs, is optional, as is the final Shutdown. The approximate mission time is 20-30 minutes, depending on the slot chosen and whether you return to base or not.\n\nThe mission requires your DCS to have the 476th Target Range Objects user Mod installed."),
    },	
{
        ["file"] = "JAS39 - Training - M13 Laser Guided Bombs (by Rudel_chw).miz",
        ["name"] = _("M13 - Laser Guided Bombs. (JAS-39C A/G)"),
        ["description"] = _("On this Training Mission we will learn the use of Laser Guided Bombs (LGB) on the Saab JAS-39C, dropping them with precision, over a set of obsolete tanks setup at Tinian’s North Field Weapons Range.\n\nWe will try two different types of laser guided bombs, dropping them in precision passes over the Range.\n\nThe Mission provides two aircraft slots to choose from:\n\n- Full Mission: Starts with the aircraft on the Ramp of Saipan airbase, already started. You must Taxi, Take-Off and Navigate to Tinian’s Weapons Range.\n\n- Air Start: You start already on the air, heading towards the Range.\n\nBefore taking one of these aircraft Slots, select the Spectators Role, to give the mission time to activate the Weapons Range script.\n\nThe return to base after delivering all LGB, is optional, as is the final Shutdown. The approximate mission time is 20-30 minutes, depending on the slot chosen and whether you return to base or not.\n\nThe mission requires your DCS to have the 476th Target Range Objects user Mod installed."),
    },
{
        ["file"] = "JAS39 - Training - M14 Air-Ground Missiles (by Rudel_chw).miz",
        ["name"] = _("M14 - Air/Ground Missiles. (JAS-39C A/G)"),
        ["description"] = _("On this Training Mission we will learn the use of Air-Ground Missiles on the Saab JAS-39C, using them to destroy a set of obsolete tanks setup at Tinian’s North Field Weapons Range.\n\nWe will try two different types of Air/Ground Missiles, launching them in precision passes over the Range:\n\n- AGM-65 Maverick: Optically Guided Missiles.\n\n- MBDA Brimstone: Laser Guided Missiles.\n\nThe Mission provides two aircraft slots to choose from:\n\n- Full Mission: Starts with the aircraft on the Ramp of Saipan airbase, already started. You must Taxi, Take-Off and Navigate to Tinian’s Weapons Range.\n\n- Air Start: You start already on the air, heading towards the Range.\n\nBefore taking one of these aircraft Slots, select the Spectators Role, to give the mission time to activate the Weapons Range script.\n\nThe return to base after launching all Missiles, is optional, as is the final Shutdown. The approximate mission time is 20-30 minutes, depending on the slot chosen and whether you return to base or not.\n\nThe mission requires your DCS to have the 476th Target Range Objects user Mod installed."),
    },
{
        ["file"] = "JAS39 - Training - M15 Anti-radar Missiles (by Rudel_chw).miz",
        ["name"] = _("M15 - Anti-radar Missiles. (JAS-39C A/G)"),
        ["description"] = _("On this Training Mission we will learn the use of the Anti-radiation Missiles on the Saab JAS-39C, using them to destroy an enemy SAM Site setup at Rota Island.\n\nThe Gripen, as simulated on DCS, can carry several different missiles that home on enemy radar emissions, on this mission we will practice with four of them:\n\nMAR-1: Anti-radiation High Speed Missile.\n\nStormshadow: Anti-radiation Cruise Missile.\n\nKEPD 350: Anti-radiation Cruise Missile.\n\nSPEAR-3: Anti-radiation missile.\n\nOther anti-radiation weapons that the Gripen can also carry on DCS are:\n\nDWS 39 MJ2: Anti-radiation stand-off cluster bomb.\n\nSPEAR-3-EW: It’s a saturation variant of the SPEAR-3.\n\nThere are two variants of this mission: you can start it at the Saipan International airbase; or you can start with the aircraft already on the air.\n\nYou need to detect radar signals and then attack the enemy SAM battery using your anti-radiation missiles. Be careful, as the enemy will try to shoot you down with their SA-11 missiles, which you will have to evade.\n\nThe return to base after launching all Missiles, is optional, as is the final Shutdown. The approximate mission time is 25-45 minutes, depending on the mission variant chosen and whether you return to base or not."),
    },	
} -- end of lessons
